name: Update and restart Botus

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Add environment variables and rebuild Botus
        run: |
          echo $'DISCORD_APP_BOT_TOKEN=${{ secrets.DISCORD_APP_BOT_TOKEN }}' >> .env
          echo $'SERVER_APP_PORT=3000' >> .env
          echo $'DISCORD_APP_INVITE_LINK=${{ secrets.DISCORD_APP_INVITE_LINK }}' >> .env
          echo $'BOT_PREFIX=-' >> .env
          echo $'BOT_NAME=Botus' >> .env
          echo $'BOT_FLAVOUR_ORIGIN=Aricarus' >> .env
          echo $'BOT_FLAVOUR_MENTOR=my old squad leader' >> .env
          echo $'BOT_FLAVOUR_DOWNTIME_ACTION_1=lights a cigarette and exhales' >> .env
          echo $'BOT_FLAVOUR_DOWNTIME_ACTION_2=lights a cigarette and puffs it' >> .env
          echo $'BOT_FLAVOUR_OLD_MOTIVATION=I was supposed to lead Ariarcus to freedom from UA control' >> .env
          echo $'BOT_FLAVOUR_OLD_MOTIVATION_2=it was about doing the right thing. Fighting for freedom and so on' >> .env
          echo $'BOT_FLAVOUR_USER_FRIENDLY_N_NICKNAME_1=buckaroo' >> .env
          echo $'BOT_FLAVOUR_OLD_MEANING_OF_LIFE=It was fighting for Aricarus, and for the freedom of my people from the clutches of UA' >> .env
          npm run build

      - name: Stop Botus and remove existing Botus build from the remote server
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.REMOTE_SERVER_HOST }}
          key: ${{ secrets.REMOTE_SERVER_PVT_KEY }}
          passphrase: ${{ secrets.REMOTE_SERVER_PASSPHRASE }}
          username: ${{ secrets.REMOTE_SERVER_USERNAME }}
          script: |
            sh stop.sh
            rm -rf botus
            mkdir botus

      - name: Copy compiled Botus build onto the remote server
        uses: appleboy/scp-action@v0.1.2
        with:
          host: ${{ secrets.REMOTE_SERVER_HOST }}
          key: ${{ secrets.REMOTE_SERVER_PVT_KEY }}
          passphrase: ${{ secrets.REMOTE_SERVER_PASSPHRASE }}
          username: ${{ secrets.REMOTE_SERVER_USERNAME }}
          source: 'dist'
          target: 'botus'

      - name: Restart Botus with updated assets
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.REMOTE_SERVER_HOST }}
          key: ${{ secrets.REMOTE_SERVER_PVT_KEY }}
          passphrase: ${{ secrets.REMOTE_SERVER_PASSPHRASE }}
          username: ${{ secrets.REMOTE_SERVER_USERNAME }}
          script: |
            sh start.sh
